sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_morning\/1.png)/![alt tag](1.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_morning\/2.png)/![alt tag](2.png/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_morning\/trimm_parameters.png)/![alt tag](trimm_parameters.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_morning\/3.png)/![alt tag](3.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/1_1.png)/![alt tag](1_1.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/picard.png)/![alt tag](picard.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/igv_zoomed_out.png)/![alt tag](igv_zoomed_out.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/igv_zoomed_in1.png)/![alt tag](igv_zoomed_in1.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/igv_zoomed_in2.png)/![alt tag](igv_zoomed_in2.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/igv_zoomed_in3.png)/![alt tag](igv_zoomed_in3.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/igv_zoomed_in4.png)/![alt tag](igv_zoomed_in4.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/igv_mgrb.png)/![alt tag](igv_mgrb.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_after\/igv_het.png)/![alt tag](igv_het.png)/g' day1_afternoon.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_morning\/plot_1.png)/![alt tag](plot_1.png)/g' day1_morning.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day1_morning\/plot_2.png)/![alt tag](plot_2.png)/g' day1_morning.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day2_morning\/intro.png)/![alt tag](intro.png)/g' day2_morning.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day2_morning\/multiqc.jpeg)/![alt tag](multiqc.jpeg)/g' day2_morning.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day2_morning\/mess.png)/![alt tag](mess.png)/g' day2_morning.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day2_morning\/beautiful.png)/![alt tag](beautiful.png)/g' day2_morning.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/day2_morning\/aligned_reads_deletion.png)/![alt tag](aligned_reads_deletion.png)/g' day2_morning.md
sed -i 's/\!\[alt tag\](https:\/\/github.com\/alipirani88\/Comparative_Genomics\/blob\/master\/_img\/spandx.jpg)/![alt tag](spandx.jpg)/g' day3_afternoon.md
